name: log_4_dart_3 # Formerly log_4_dart_2 at https://github.com/Ephenodrom/Dart-Log-4-Dart-2
description: A dart package for logging, with multiple and configurable appenders.
version: 3.0.0
homepage: https://github.com/raoulsson/log4dart3

# version tweaked by raoulsson.com. https://github.com/raoulsson/Dart-Log-4-Dart-2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  analyzer: ^7.3.0
  basic_utils: ^5.8.2
  intl: ^0.19.0
  mailer: ^6.4.1
  meta: ^1.10.0
  mysql1: ^0.20.0
  coverage: ^1.7.0
  vm_service: ^15.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.24.8

